name: deploy

on: 
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update on server
      run: |
        echo '${{ secrets.SSH }}' > /dev/tmp/id_rsa
        chmod 600 /dev/tmp/id_rsa
        ssh -i "aws-telegram-bot.pem" ubuntu@ec2-18-196-110-178.eu-central-1.compute.amazonaws.com
        cd /home/ubuntu/maya-py-telegram-bot/telegrambot.py
        git pull
        sudo systemctl restart mayabot.service
        exit
        
    - name: Cleaning
      run: |
        rm -r /dev/tmp/id_rsa
