name: deploy

on: 
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Lazy deploy
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /home/ubuntu/maya-py-telegram-bot/
          git pull
          sudo systemctl restart mayabot.service
          
        host: ${{ secrets.HOST }}
        user: ubuntu
        key: ${{ secrets.SSH}}
